language: generic
matrix:
  include:
    - script:
        - set -o pipefail && script/cibuild | xcpretty
        - bundle exec pod lib lint SwiftLintFramework.podspec
      env: JOB=Xcode
      os: osx
      osx_image: xcode9
      before_install:
        - bundle install
        - bundle exec pod repo update
    - script: swift test --parallel
      env: JOB=SPM
      os: osx
      osx_image: xcode9
    - script: make docker_test
      env: JOB=Linux4.0
      sudo: required
      services: docker
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
after_success:
  - bash <(curl -s https://codecov.io/bash)
