language: objective-c
osx_image: xcode7.2
git:
  submodules: false
branches:
  only:
    - master
script: script/cibuild | xcpretty
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
