language: objective-c
git:
  submodules: false
branches:
  only:
    - master
script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681
matrix:
  include:
    - script:
        - set -o pipefail && script/cibuild | xcpretty
        - pod lib lint
      osx_image: xcode8
      env: JOB=Xcode8
      before_install:
        - gem install cocoapods -v '1.1.1'
        - pod repo update
    - script: swift test
      osx_image: xcode8
      env: JOB=SPM
  exclude:
    - script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681

notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
after_success:
  - bash <(curl -s https://codecov.io/bash)
